backend:
  name: git-gateway
  branch: master

media_folder: static/images
public_folder: /images

publish_mode: editorial_workflow

collections:
  - name: 'writing'
    label: 'Writing'
    folder: 'src/pages'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'string', pattern: ['^\d{4}\-(0[1-9]|1[012])\-(0[1-9]|[12][0-9]|3[01])$', 'Date must be in YYYY-MM-DD format']}
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }