name: Daily Netlify Build

on:
  schedule:
    # Run at 0400 daily (AZ time)
    - cron: '0 11 * * *'

jobs:
  request:
    name: Request Build
    runs-on: ubuntu-latest

    steps:
      - name: Send cURL request
        run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK }}
